# Generated by Django 5.0.2 on 2024-02-26 09:14

import chat_server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_server', '0003_alter_server_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=chat_server.models.server_banner_upload),
        ),
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=chat_server.models.server_icon_upload),
        ),
    ]
